### ISSUE TITLE
standalone_static won't compile on Windows

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#360] opened 2021-01-20 05:55 UTC
On Windows, a simple `pyoxidizer.bzl` that just picks the [`standalone_static` flavor](https://pyoxidizer.readthedocs.io/en/v0.10.3/config_type_python_distribution.html#default-python-distribution). 

```bzl
def make():
    dist = default_python_distribution(flavor="standalone_static")
    return dist.to_python_executable(
        name="pyapp",
        packaging_policy=dist.make_python_packaging_policy(),
        config=dist.make_python_interpreter_config(),
    )
register_target("install", make, default=True)
resolve_targets()
```

`pyoxidizer build` produces so many linker warnings that the output exceeds GitHub's 2<sup>16</sup> character limit, but the interesting part is the following.
```
          libpyembed-99009795ae575a74.rlib(callproc.obj) : error LNK2019: unresolved external symbol ffi_prep_cif referenced in function _call_function_pointer
          libpyembed-99009795ae575a74.rlib(callbacks.obj) : error LNK2001: unresolved external symbol ffi_prep_cif
          libpyembed-99009795ae575a74.rlib(callproc.obj) : error LNK2019: unresolved external symbol ffi_call referenced in function _call_function_pointer
          libpyembed-99009795ae575a74.rlib(callbacks.obj) : error LNK2019: unresolved external symbol ffi_prep_closure_loc referenced in function _ctypes_alloc_callback
          %TMP%\pyoxidizer27JmHU\build\target\x86_64-pc-windows-msvc\debug\deps\pyapp.exe : fatal error LNK1120: 3 unresolved externals
```
`ffi_prep_cif`, `ffi_call`, and `ffi_prep_closure_loc` are each exported from `libffi-7.dll`, which is included with the `standalone_dynamic` flavor distribution (this is verifiable with the [`dumpbin /exports`](https://docs.microsoft.com/en-us/cpp/build/reference/dash-exports) command, but I'm omitting the output for now.)

I'm on Windows 10 with Visual Studio 2019 Build Tools, `cl.exe` version 19.26.28806 for x64, `link.exe` version 14.26.28806.0, and pyoxidizer is built from 357bbc3808f7868f86814b7e17ed28598bc0402a (current tip of #343).

**Comment by indygreg** [comment] 2021-01-23 18:06
Static libffi on Windows was a pain to get working. This likely regressed as part of updating the Python distributions and its regression can be traced back to a change in indygreg/python-build-standalone. I also thought we had a test for the static distributions to ensure they kept working. I guess not :/ We should definitely add a test that builds a binary from the Windows static distribution.

In recent weeks, I've added Rust code to python-build-standalone to verify the correctness of the built distributions. It does things like look at required library dependencies and symbols. We should probably teach this verification code to ensure that the libffi symbols are proper.

I don't have access to my Windows machine at the moment. Would you be able to bisect this failure? I'd start by looking at the commits that change `pyoxidizer/src/python_distributions.rs`. If not, I can probably figure it out by writing the aforementioned symbol verification code and find which distribution introduced a change in behavior.

**Comment by wkschwartz** [comment] 2021-01-25 17:09
It'll be awhile before I would be able to get to this since my project can't use static linking as long as it doesn't support importing external extension modules (`.pyd`s). In case someone else can get to this first, do you have a guess about the last working commit? Would it have been the v0.10.3 tag?

**Comment by indygreg** [comment] 2021-02-28 01:40
I'm guessing this regressed as part of updating the default Python distributions. Do a `git log -- pyoxidizer/src/python_distributions.rs` and test commits changing the Windows distributions.

Heads up: I'll likely update the default distributions soon. With any luck, this went away with 3.8.8/3.9.2. In either case, I'd love to teach the binary analysis Rust code in python-build-standalone to validate the correctness of problematic symbols in the binaries. Keeping this behavior consistent is difficult, which is why we have code for validating low-level details of binaries.

**Comment by indygreg** [comment] 2021-03-02 22:53
I'm able to reproduce this.

Some ffi symbols aren't present in any of the `.obj` files for the `_ctypes` extension (or in `_ctypes.lib` by extension). But these object files are referencing symbols like `ffi_prep_cif`.

The compile command is as follows:

```
     4>ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\CL.exe /c /I"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\libffi\include" /I"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\Include" /I"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\Include\internal" /I"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PC" /I"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\\" /Zi /nologo /W3 /WX- /diagnostics:column /O2 /Oi /D Py_BUILD_CORE_BUILTIN /D FFI_BUILDING /D Py_NO_ENABLE_SHARED /D WIN32 /D "PY3_DLLNAME=L\"python3\"" /D _WIN64 /D _M_X64 /D NDEBUG /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\\" /Fd"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\_ctypes.pdb" /Gd /TC /FC /errorReport:queue /utf-8 ..\Modules\_ctypes\_ctypes.c ..\Modules\_ctypes\callbacks.c ..\Modules\_ctypes\callproc.c ..\Modules\_ctypes\cfield.c ..\Modules\_ctypes\malloc_closure.c ..\Modules\_ctypes\stgdict.c
```

The archiver command is as follows:

```
     4>Lib:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\Lib.exe /OUT:"C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCbuild\amd64\_ctypes.lib" /NOLOGO /MACHINE:X64 /LTCG /EXPORT:DllGetClassObject,PRIVATE /EXPORT:DllCanUnloadNow,PRIVATE "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\python_nt.res"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\_ctypes.obj"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\callbacks.obj"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\callproc.obj"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\cfield.obj"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\malloc_closure.obj"
         "C:\Users\gps\AppData\Local\Temp\python-build-8erlb6qp\Python-3.9.2\PCBuild\obj\39amd64_Release\_ctypes\stgdict.obj"
```

Notably missing from these invocations is a reference to `libffi.lib`.

When/why this regressed, I'm not sure. I'd like to dig up an old release to track down when things went wrong. But I think correcting it is a matter of ensuring `libffi.lib` is brought into `_ctypes.lib`, adding `libffi.lib` to the distribution, and referencing this as a static library dependency of the `_ctypes` extension.

**Comment by indygreg** [comment] 2021-03-02 23:30
If we look at old python-build-standalone distributions (e.g. https://github.com/indygreg/python-build-standalone/releases/download/20200408/cpython-3.7.7-windows-amd64-static-20200409T0105.tar.zst), we see that the `_ctypes` extension has object files like `ffi.obj` and `prep_cif.obj`. These correspond to source files from libffi.

However, if we go back to the first version of the static builds for 3.8 (e.g. https://github.com/indygreg/python-build-standalone/releases/download/20200517/cpython-3.8.3-x86_64-pc-windows-msvc-static-noopt-20200517T2203.tar.zst), these files are gone. This probably has something to do with https://bugs.python.org/issue35947 and the related work to remove libffi from the source repo. So it looks like python-build-standalone has been buggy w.r.t. libffi symbols since it started shipping 3.8 distributions.

What's really odd is that I can get things to compile against a static 3.8 distribution though. Why, I'm not sure. I suspect we got lucky and picked up the symbols from elsewhere. Or maybe PyOxidizer changed how it links distributions. I can't recall. Regardless, I'm pretty confident the python-build-standalone distributions are to blame for this. And we obviously are lacking test coverage of this build configuration.

**Comment by indygreg** [comment] 2021-03-03 01:36
Well, I didn't mean to close this. But I guess GitHub's comment sniffing had other ideas.

This will require a change to PyOxidizer to pick up the new Windows distributions. But those are building as I type this. So things should land in a few hours.

**Comment by indygreg** [comment] 2021-03-03 02:36
I found a separate unresolved symbol issue on Windows. Given how long it takes CI to crank out builds, I may not have new Windows distributions published until tomorrow.

**Closed** 2021-03-04 00:12 UTC
Labels: bug
