### ISSUE TITLE
Build error on Ubuntu 18.04

### ISSUE THREAD

**Issue by joedougherty** [indygreg/PyOxidizer#12] opened 2019-06-24 19:11 UTC
I installed rust and cargo via rustup and installed pyoxidizer via cargo.

`rustc --version: rustc 1.35.0 (3c235d560 2019-05-20)`

`cargo --version: cargo 1.35.0 (6f3e9c367 2019-04-04)`

`$ pyoxidizer init pyapp`
`$ cd pyapp`
`$ pyoxidizer build` 

results in...

```
    Updating crates.io index
    Updating git repository `https://github.com/indygreg/PyOxidizer.git`
error: failed to load source for a dependency on `cpython`

Caused by:
  Unable to update https://github.com/indygreg/PyOxidizer.git?rev=

Caused by:
  failed to parse revision specifier - Invalid pattern ''; class=Invalid (3); code=InvalidSpec (-12)
error: cargo build failed
```

**Comment by indygreg** [comment] 2019-06-24 19:51
This looks to be a duplicate of #11. I'll comment in that issue shortly...

**Closed by indygreg** 2019-06-24 19:51 UTC
