### ISSUE TITLE
thread 'main' paniched at 'already borrowed: Borrowed' ...starlark-0.3.1

### ISSUE THREAD

**Issue by ryancinsight** [indygreg/PyOxidizer#315] opened 2020-11-06 20:00 UTC
Windows 10
Pyoxidizer 0.10pre downloaded 11/6/2020
side note 0.9 works

Example:
just running pyoxidizer run with no changes:

Results Backtrace=full:
thread 'main' panicked at 'already borrowed: Borrowed', C:\Users\RyanM\.cargo\registry\src\github.com-1ecc6299db9ec823\starlark-0.3.1\src\values\mod.rs:1347:23
stack backtrace:
   0:     0x7ff6913811c9 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6913811c9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6913811c9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff6913811c9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff6913a211b - core::fmt::write
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
   5:     0x7ff691377344 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
   6:     0x7ff69138472b - std::sys_common::backtrace::_print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff69138472b - std::sys_common::backtrace::print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff69138472b - std::panicking::default_hook::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
   9:     0x7ff691384369 - std::panicking::default_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
  10:     0x7ff691384f0f - std::panicking::rust_panic_with_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
  11:     0x7ff691384a75 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:476
  12:     0x7ff691381a7f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff691384a29 - std::panicking::begin_panic_handler
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
  14:     0x7ff6913849dc - std::panicking::begin_panic_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
  15:     0x7ff690b5dfdb - starlark::values::Value::downcast_mut::hae34a429654282db
  16:     0x7ff690abc147 - pyoxidizer::starlark::eval::EvaluationContext::build_resolved_target::hed495f9e99f52a4b
  17:     0x7ff690abdfe5 - pyoxidizer::starlark::eval::EvaluationContext::run_target::h058cdb61d5b26c51
  18:     0x7ff690a881aa - pyoxidizer::projectmgmt::run::h4afa4c56f998990e
  19:     0x7ff690ba9e3c - pyoxidizer::cli::run_cli::h9d7057ffb63ff1fa
  20:     0x7ff690a91a77 - pyoxidizer::starlark::env::global_environment::h3dd2b6ae104fa0f4
  21:     0x7ff690aed196 - handlebars::error::RenderError::new::h6016f860080f0829
  22:     0x7ff690aed1ac - std::rt::lang_start::{{closure}}::h82f7a089e7de7ce3
  23:     0x7ff691385116 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
  24:     0x7ff691385116 - std::panicking::try::do_call
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
  25:     0x7ff691385116 - std::panicking::try
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
  26:     0x7ff691385116 - std::panic::catch_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
  27:     0x7ff691385116 - std::rt::lang_start_internal
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
  28:     0x7ff690a91b27 - main
  29:     0x7ff6914dd4c4 - invoke_main
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30:     0x7ff6914dd4c4 - __scrt_common_main_seh
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31:     0x7ffe19ba7034 - BaseThreadInitThunk
  32:     0x7ffe1a75cec1 - RtlUserThreadStart

**Comment by indygreg** [comment] 2020-11-06 21:35
Is this a duplicate of #314? The stack looks like it is.

Could you please confirm this still reproduces on the latest commit on the `main` branch?

**Comment by ryancinsight** [comment] 2020-11-06 21:41
Originally, I was getting #314 but this is after downloading:
$ cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer

after you closed that issue. I'm not seeing the Result error either now.

**Comment by indygreg** [comment] 2020-11-06 22:28
Then this was likely a duplicate. Yay!

**Closed by indygreg** 2020-11-06 22:28 UTC

**Comment by ryancinsight** [comment] 2020-11-06 22:34
Sorry I believe I said that wrong...

Instead of getting thread 'main' panicked at 'called Result::unwrap...

Im now getting at thread 'main' panicked at 'already borrowed...

I'm still getting this new error after updating. I apologize for confusion.

**Comment by pouyamiralayi** [comment] 2020-11-09 06:59
> Sorry I believe I said that wrong...
> 
> Instead of getting thread 'main' panicked at 'called Result::unwrap...
> 
> Im now getting at thread 'main' panicked at 'already borrowed...
> 
> I'm still getting this new error after updating. I apologize for confusion.

@indygreg I'm also getting this error while running with: `pyoxidizer run`

OS:                      UBUNTU 18.04.3
Architecture:        x86_64
PyOxidizer:          0.10.0-pre-562ac88d2749bfffd30e40368a27c2be77ff054b

**Comment by indygreg** [comment] 2020-11-10 03:49
Turns out there was a separate double borrow bug. I have a commit ready locally and I should push it tonight. Thanks for keeping me honest!

**Comment by ryancinsight** [comment] 2020-11-10 13:19
@indygreg is this implemented in v0.10.1 or v0.11.0 pre? The first is saying error: failed to select a version for the requirement `pyembed = "^0.10.1"` and the second option seems to build but the python interpreter doesn't seem to open and when I run executable it seems to instantly close?
