### ISSUE TITLE
import unicodedata fails with PyOxidizer 0.8.0-pre on Windows

### ISSUE THREAD

**Issue by mardukbp** [indygreg/PyOxidizer#249] opened 2020-05-05 20:50 UTC
I installed PyOxidizer 0.8.0-pre using the HEAD of the master branch and built the simple project from the docs, that yields a self-contained Python 3.8.2 interpreter.

In the Python prompt I entered `import unicodedata` and obtained the error

`ModuleNotFoundError: No module named 'unicodedata'`

With the stable release of PyOxidizer, version 0.7.0, which uses Python 3.7.7, this statement works.

**Comment by mardukbp** [comment] 2020-05-05 22:11
This issue gets solved setting `filesystem_importer=True` in `pyoxidizer.bzl`.

**Comment by indygreg** [comment] 2020-05-17 02:41
This sounds like a subtle regression in the unreleased version with regards to registration of the filesystem importer in a default or near-default configuration. Although I'm not yet sure if it is desired or not. (We will likely change some behaviors in the next release to accommodate new APIs in Python 3.8.)

What example did you use to trigger this new behavior?

**Comment by mardukbp** [comment] 2020-05-17 18:59
I just did the following on macOS 10.13:

1. `cargo install --git https://github.com/mardukbp/PyOxidizer.git --branch v0.8.0-pre-workaround pyoxidizer`

This is the main branch from upstream (12 days behind the current HEAD) with the following patch applied (without this patch `pyoxidizer run` fails because it cannot find `pyembed` version 0.8.0-pre)

```diff
diff --git a/pyoxidizer/src/project_layout.rs b/pyoxidizer/src/project_layout.rs
index 0b642304..88972f98 100644
--- a/pyoxidizer/src/project_layout.rs
+++ b/pyoxidizer/src/project_layout.rs
@@ -266,7 +266,7 @@ pub fn update_new_cargo_toml(path: &Path, pyembed_location: &PyembedLocation) ->
 
     content.push_str(&match pyembed_location {
         PyembedLocation::Version(version) => format!(
-            "pyembed = {{ version = \"{}\", default-features=false }}\n",
+            "pyembed = {{ version = \"{}\", default-features=false, git = 'https://github.com/indygreg/PyOxidizer', branch = 'main' }}\n",
             version
         ),
         PyembedLocation::Path(path) => format!(
```

2. `mkdir pyapp`
3. `pyoxidizer init-config-file pyapp`
4. `cd pyapp`
5. `pyoxidizer run`

When the compilation finished and the executable ran I entered `import unicodedata` and it worked. I think the issue I reported occurs only with a dynamic Python build.

Since apparently you will soon provide [static Python 3.8 binaries for Windows](https://github.com/indygreg/python-build-standalone/pull/40#issuecomment-629828769), I will test again and report back here.

**Comment by indygreg** [comment] 2020-10-05 03:18
I believe this was due to poor handling/preserving of extension module file suffixes. I've pushed a fix to the `main` branch in the past week that should fix this and there is now test coverage that this should work (at least on Windows).

Also, the bad reference to the `pyembed` crate should hopefully be fixed on the `main` branch as well.

Can you please `cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer` and report if things are fixed?

**Comment by indygreg** [comment] 2020-10-09 23:20
I can reproduce this. `unicodedata` is a built-in extension module. I'm really curious why it isn't working. I'll try to find time to investigate this weekend.

**Closed** 2020-10-11 02:16 UTC
Labels: bug

**Comment by mardukbp** [comment] 2020-10-11 17:11
Great job @indygreg! Thank you!
