### ISSUE TITLE
ModuleNotFoundError: No module named 'rich.__init__'

### ISSUE THREAD

**Issue by GTxx** [indygreg/PyOxidizer#317] opened 2020-11-09 03:06 UTC
Hi, 
I got a cli package which uses [rich](https://github.com/willmcgugan/rich) to prettify the terminal output, this package works fine with pyoxidizer=0.7.
But after upgrading pyoxidizer to 0.9, it throws exception as below:
```sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test_rich.main", line 2, in <module>
  File "rich.table", line 8, in <module>
  File "rich.jupyter", line 4, in <module>
ModuleNotFoundError: No module named 'rich.__init__'
```

I have created a repo here: https://github.com/GTxx/test_rich for reproducing the error.

Thanks

**Comment by Alex-Mann** [comment] 2020-11-17 20:00
I am also hitting this same issue. Does anyone know if there is a missing required property in the pyoxidizer.bzl file so that it knows how to find packages?

**Comment by href** [comment] 2020-11-27 16:23
I got it as well. All that is needed to reproduce is a `pyoxidizer.bzl` with `pip_install(['rich'])`. After building the interpreter run `import rich.jupyter` and the error should show.

I wonder if this is a corner case related to the custom importer, because in all my years of Python I don't think I've ever came across this construct:

```
from .__init__ import get_console
```
See https://github.com/willmcgugan/rich/blob/15870cee965ccd75a4f9b1854bb92753620d0fdb/rich/jupyter.py#L4

Usually you'd see something like `from . import get_console`, at least in my experience.

Anyway, interested in a fix or a workaround as well. I can't get this to work at all.

**Comment by indygreg** [comment] 2020-11-27 22:57
That `from .__init__ import get_console` line is really wonky! I'm surprised that even works. And I'm guessing it works due to some quirk with how the module importer resolves files. I'm willing to bet that `rich` and `rich.__init__` are two separate modules from the perspective of the Python interpreter. But I'll need to test to confirm. Depending on the results, this is either a legit bug or possibly a _won't fix_. I'd really prefer to avoid dealing with this edge case if possible. Although it might not be too difficult to implement.

Since this construct is really wonky, would somebody mind filing an issue against `rich` and trying to convince them to change their code? I can't imagine any scenario in which this construct is actually required...

**Comment by href** [comment] 2020-12-01 12:10
Looks like this has been fixed in `rich`, thank you @GTxx!

**Comment by href** [comment] 2020-12-01 12:12
Do note, that this seems to be somewhat widespread, at least on GitHub:
https://github.com/search?q=%22from+.__init__+import%22&type=Code

So this might pop up again in the future in some other package - it seems to be something CPython actually supports.

**Comment by indygreg** [comment] 2020-12-04 01:59
Go home, Python: you're drunk:

```
$ mkdir foo
$ cat > foo/__init__.py <<EOF
> test = True
> EOF
$ cat > foo/bar.py <<EOF
> from .__init__ import test
> EOF
$ python3.9
Python 3.9.0 (default, Nov  1 2020, 22:40:00)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo.bar
>>> import sys
>>> sys.modules['foo']
<module 'foo' from '/home/gps/tmp/pyinit-test/foo/__init__.py'>
>>> sys.modules['foo.__init__']
<module 'foo.__init__' from '/home/gps/tmp/pyinit-test/foo/__init__.py'>
```

As I feared, Python's filesystem based importer isn't smart enough to detect the `from .__init__ import ...` syntax and normalize away the `__init__` part. This leads to 2 separate versions of the same file being imported under 2 module names. In this case, `foo` and `foo.__init__`.

Since Python supports this syntax, I guess I'll need to teach PyOxidizer to handle it as well. It should be relatively easy to detect a trailing `__init__` on the module name and normalize to its parent automatically. The big question is whether I should support Python's behavior of creating a 2nd module for the same thing or just silently alias. I want to do the right thing and alias the name silently. But there could be code in the wild relying on subtle behavior differences due to the existence of multiple module objects.

**Comment by indygreg** [comment] 2020-12-04 02:12
I filed a Python issue for this, as I feel it warrants the attention of Python's core developers.

https://bugs.python.org/issue42564

**Closed** 2020-12-04 03:17 UTC
Labels: bug

**Comment by indygreg** [comment] 2020-12-04 03:24
I pushed a patch for this that makes PyOxidizer partially compatible with CPython's behavior. I think this will be sufficient for code in the wild. But I'm not 100% convinced.

Please read the comments and documentation in bd20ae7 and leave a comment here if you feel the approach is not reasonable.

I would be ecstatic if a CPython maintainer weighed in on the upstream bug report and clarified the expected behavior (preferably via a docs change or code patch) so I could follow CPython's lead and fully converge on behavior. As it stands, I think CPython is buggy and I'd prefer not to reimplement that buggy behavior any more than I need to. But if CPython says it is a feature instead of a bug, I'll (begrudgingly) go along.

Without guidance from CPython, I also might be receptive to converging behavior if someone can point out code in the wild that isn't compatible with the solution as implemented.
