### ISSUE TITLE
Following steps for Customizing Python and Packaging Behavior produces error

### ISSUE THREAD

**Issue by srufle** [indygreg/PyOxidizer#137] opened 2019-09-29 19:25 UTC
**Platform:**
Ubuntu 18.04
Installed PyOxidizer 0.3.0 through cargo 

Was able to run the first part where you run the repl. Then made the changes to eval some simple code. 
```
[[embedded_python_run]]
mode = "eval"
code = "import uuid; print(uuid.uuid4())"
```
Ran :
`RUST_BACKTRACE=1 pyoxidizer run`
produced a lot of output so I made gist
https://gist.github.com/srufle/e45eb04fcd51d50f683022855079f810

**Comment by GonzRon** [comment] 2019-10-03 00:25
try running it with sudo
the error appears to be 
`thread 'main' panicked at 'unable to copy library file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5`

**Comment by srufle** [comment] 2019-10-03 06:42
@GonzRon I updated my gist
https://gist.github.com/srufle/e45eb04fcd51d50f683022855079f810

Created a test-pyox.sh to show the issue. It does look like a permissions issue, but I was unable to figure out why after a successful build just touching the pyoxidizer.toml and asking to run again, would cause the issue.

**Comment by lithp** [comment] 2019-10-03 13:36
Duplicate of this issue: https://github.com/indygreg/PyOxidizer/issues/123

As a workaround you can either run `chmod -R +m` or `rm` the offending files before each time you rerun PyOxidizer.

**Comment by abulka** [comment] 2019-10-05 13:17
Following the PyOxidizer tutorial and having the first recommended alteration to the default project fail in this way is frustrating. Even if you find your way to this issue #137 and #123 its still not clear to me how to workaround the problem.

The recommended commands `chmod -R +m` and `find python -not -perm /u+w -ls` don't work on Mac. As for `rm` the offending files - how do I know which are the offending files? What I see is:

```
static library tk8.6 required by _tkinter
static library uuid required by _uuid
static library z required by zlib
resolving inputs for 0 built extension modules...
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libbz2.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libcrypto.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libdb.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libffi.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/liblzma.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libsqlite3.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libssl.a
/Users/Andy/Devel/pyoxidiser_demo1/pyapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.4a77d5ca8981/python/build/lib/libtcl8.6.a
thread 'main' panicked at 'unable to copy library file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I cannot see any existing file named `Os` in my directory heirarchy, or am I misreading the error message?

**Comment by GonzRon** [comment] 2019-10-05 13:30
I think 0s means zero seconds, though I could be wrong.
Note the message:
```run with `RUST_BACKTRACE=1` environment variable to display a backtrace.```

**Comment by abulka** [comment] 2019-10-05 13:56
Running with the trace flag adds the following:

```
thread 'main' panicked at 'unable to copy library file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1084:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: pyoxidizer::pyrepackager::repackage::link_libpython
   8: pyoxidizer::pyrepackager::repackage::process_config
   9: pyoxidizer::projectmgmt::build_pyoxidizer_artifacts
  10: pyoxidizer::projectmgmt::build_project
  11: pyoxidizer::projectmgmt::run
  12: pyoxidizer::cli::run_cli
  13: pyoxidizer::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: main
```

Not sure that helps determine which file(s) have the wrong permission?

**Comment by indygreg** [comment] 2019-10-27 02:17
This is due to bad permissions in the Python distributions that PyOxidizer uses. It will be fixed in the next PyOxidizer version.

In the mean time, you can change your `pyoxidizer.toml` to point to newer Python distributions: https://github.com/indygreg/PyOxidizer/commit/36cd5027d2666d582005562f4dba8b24cd9fa449

**Closed by indygreg** 2019-10-27 02:17 UTC
