### ISSUE TITLE
Problem in adding pandas module in pyoxidizer.toml

### ISSUE THREAD

**Issue by pksingh2612** [indygreg/PyOxidizer#131] opened 2019-09-18 14:55 UTC
just try any pandas program to deploy
"I am adding the following code in pyoxidizer.toml file"

[[packaging_rule]]
type="pip-install-simple"
package="pandas"

and it will run in the following manner and after some moment
----------------------------------------------------------------------------------

 (from python-dateutil>=2.6.1->pandas)
  Using cached https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz
Skipping bdist_wheel for python-dateutil, due to binaries being disabled for it.
Installing collected packages: six, python-dateutil, pytz, numpy, pandas
  Running setup.py install for six: started
    Running setup.py install for six: finished with status 'done'
  Running setup.py install for python-dateutil: started
    Running setup.py install for python-dateutil: finished with status 'done'
  Running setup.py install for pytz: started
    Running setup.py install for pytz: finished with status 'done'
  Running setup.py install for numpy: started
    Running setup.py install for numpy: still running...

I am getting the following error :
-----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\pksin\pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python.82ae15f31178\python\install\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pksin\\AppData\\Local\\Temp\\pip-install-q02h7me5\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\pksin\\AppData\\Local\\Temp\\pip-install-q02h7me5\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pksin\AppData\Local\Temp\pip-record-kh6q_w54\install-record.txt' --single-version-externally-managed --compile '--home=C:\Users\pksin\AppData\Local\Temp\pip-target-z2f6db_p' Check the logs for full command output.
thread 'main' panicked at 'error running pip', C:\Users\pksin\.cargo\registry\src\github.com-1ecc6299db9ec823\pyoxidizer-0.3.0\src\pyrepackager\packaging_rule.rs:889:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by danfulton** [comment] 2019-09-23 23:51
I'm having a similar issue, trying to install pandas in a `requirements.txt`.  In my `pyoxidizer.toml` I have...
```
[[packaging_rule]]
type = "pip-requirements-file"
requirements_path = "requirements.txt"
```
... and in my requirements file I have a single line `pandas==0.24.0`.
The resulting error is
```
 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\me\scratch_local\probingPostProcess\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python.82ae15f31178\python\install\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\1\\pip-install-023ucfax\\pandas\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\1\\pip-install-023ucfax\\pandas\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\me\AppData\Local\Temp\1\pip-install-023ucfax\pandas\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "C:\Users\me\scratch_local\probingPostProcess\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python.82ae15f31178\python\install\lib\site-packages\setuptools-41.0.1-py3.7.egg\pkg_resources\__init__.py", line 359, in get_provider
    KeyError: 'numpy'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\me\AppData\Local\Temp\1\pip-install-023ucfax\pandas\setup.py", line 732, in <module>
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "C:\Users\me\AppData\Local\Temp\1\pip-install-023ucfax\pandas\setup.py", line 475, in maybe_cythonize
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "C:\Users\me\scratch_local\probingPostProcess\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python.82ae15f31178\python\install\lib\site-packages\setuptools-41.0.1-py3.7.egg\pkg_resources\__init__.py", line 1144, in resource_filename
      File "C:\Users\me\scratch_local\probingPostProcess\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\python.82ae15f31178\python\install\lib\site-packages\setuptools-41.0.1-py3.7.egg\pkg_resources\__init__.py", line 361, in get_provider
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
thread 'main' panicked at 'error running pip', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pyoxidizer-0.3.0\src\pyrepackager\packaging_rule.rs:1023:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by danfulton** [comment] 2019-09-23 23:59
For newer versions `pandas=0.24.2` and `pandas==0.25.0` pyOxidizer spends much longer trying to install `numpy` and then ultimately fails with a much longer error message.

**Comment by danfulton** [comment] 2019-09-24 15:48
I think this is ultimately related to Issue #65 Unable to use numpy.

**Comment by indygreg** [comment] 2019-10-27 03:22
Yeah, this feels like a dupe of #65.

**Closed by indygreg** 2019-10-27 03:22 UTC
