### ISSUE TITLE
Embedded python kernel hangs in some scenarios

### ISSUE THREAD

**Issue by katetsu** [indygreg/PyOxidizer#480] opened 2021-11-23 20:06 UTC
I am experiencing a scenario where the second call to `acquire_gil` hangs. i have tried both using `acquire_gil` followed by a `release_gil` as well as `pyo3::with_gil(...)` and the results are the same.

My tests with multiple calls to `acquire/release gil` do pass but my application which uses async context and some multi threading is showing the above issue.

My application and tests both use the interpreter with static lifetime. `MainPythonInterpreter<'static, 'static>` could this cause an issue?

also, i have the ability to switch to using an external kernel using pyo3 and that is not having the same issue.

In general how could i debug this further?

**Comment by indygreg** [comment] 2021-11-24 02:28
I'd need to look at your code.

If you have a reference to a `pyembed::Python` instance, that will hold the GIL. If `acquire_gil` hangs, that's presumably because the GIL is already held.

There may be some lifetime annotations incorrectly defined in `pyembed` enabling programs to compile when they shouldn't. It is also likely possible to mix `pyembed` and `pyo3` APIs in a way that leads to deadlock.

The direction `pyo3` is going - and likely where I'll take `pyembed` - is to use a callback to execute Python code. The thing executing the callback handles acquiring the GIL. That helps prevent dangling GIL acquisitions and potential for deadlock.

**Comment by katetsu** [comment] 2021-11-24 10:22
I have added you to a repo where this issue is visible. https://github.com/katetsu/pyembed-issue

**Comment by katetsu** [comment] 2021-12-02 16:32
any hope?

**Comment by indygreg** [comment] 2022-01-29 02:16
I just refactored a lot of code related to GIL handling as part of #500. That code is on the `main` branch now and will be part of the `0.20` release. I suspect these changes will make the deadlock issue go away as long as you are using the APIs on `pyembed::MainPythonInterpreter` to interact with the interpreter. If you are calling unsafe APIs, you could still shoot yourself in the foot and cause deadlock. But this was always the case: it's called `unsafe` for a reason :)

I'm going to close this since I think it was addressed by #500. Please reopen if you can still reproduce.

**Closed by indygreg** 2022-01-29 02:16 UTC
